<a href="https://colab.research.google.com/github/ilovesylus/mathcomputer/blob/main/Assignment_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 8

#### Student ID: B132045005
#### Name: 李子玉


### (1) Which of the following statement is False?

(A) A `@classmethod` takes `cls` as the first parameter and can be called by both the class and its instances.       

(B) A `@classmethod` is commonly used to create alternate constructors for the class.   

(C) A `@classmethod` can access and modify instance attributes like `self.name` and `self.age`.

(D) A `@classmethod` can be used to create an instance from a formatted string.

> Ans: C

### (2) Which of the following statement is False?

(A) Polymorphism allows different classes to define methods with the same name that behave differently.

(B) Built-in functions like `len()` exhibit polymorphism because they work on different types like strings and lists.

(C) Operator overloading using methods like `__add__` and `__eq__` is also a kind of polymorphism.

(D) In polymorphism, a child class must use the `super()` function when overriding a parent class method.

> Ans: D

### (3) Which of the following statement is False?

(A) `NumPy` arrays are statically typed, meaning all elements must be of the same data type.    

(B) The `dtype` attribute of a `NumPy` array tells us the type of elements stored in the array.

(C) The `size` attribute of a `NumPy` array indicates the number of bytes used to store each element.

(D) The `zeros()`, `ones()` and `full()` functions can all specify the desired array shape and data type.

> Ans: C

### (4) Which of the following statement is False?

(A) `np.array([1, 2, 3])` creates a 1D NumPy array containing integers.     
(B) `np.array([[1, 2], [3, 4]])` creates a 2D array with shape `(2, 2)`.     
(C) The shape of `np.array([5.5, 6.2, 7.1])` is `(3, 1)` because it contains three elements.     
(D) All elements in a NumPy array must have the same data type.          

> Ans: C

### (5) Which of the following statement is False?

(A) The `dtype` of an array can be explicitly specified when using `np.ones()` or `np.zeros()` functions.      
(B) The function `np.full((2, 3), 7)` creates a 2-by-3 array with all elements equal to 7.       
(C) The number of dimensions in an array can be accessed using the `shape` attribute.           
(D) The `size` attribute of a NumPy array indicates the number of bytes used to store the entire array.        

> Ans: C

### (6) Suppose we are developing a smart city parking system, and we want to model a ParkingLot class that tracks the number of total lots in the city. Each individual lot has its own name and capacity.

Please complete the ParkingLot class below using a class method to create a new lot from a given string that encodes the name and capacity (separated by a comma), and ensure that each time a new lot is created, the total count of lots increases.

**Example Output:**     
KaohsiungLot 120  
TainanLot 85  
Total lots: 2


In [ ]:
# Define the ParkingLot class here
class ParkingLot:
    total_lots = 0
    def __init__(self, name, capacity):
        self.name = name
        self.capacity = int(capacity)
        ParkingLot.total_lots += 1
    @classmethod
    def from_string(cls, lot_string):
        name, capacity = lot_string.split(",")
        return cls(name.strip(), int(capacity.strip()))


In [ ]:
# Test your class
lot1 = ParkingLot.from_string("KaohsiungLot,120")
lot2 = ParkingLot.from_string("TainanLot,85")
print(lot1.name, lot1.capacity)
print(lot2.name, lot2.capacity)
print("Total lots:", ParkingLot.total_lots)

KaohsiungLot 120
TainanLot 85
Total lots: 2


### (7) Suppose we are designing a simple animal sound simulator. There is a base class Animal that has a method speak(). Different animals will override this method to return different sounds.

**Example Output:**      
Woof!      
Meow!       
...    


Please complete the following classes so that they demonstrate polymorphic behavior:

In [ ]:
# Define the base class Animal
class Animal:
    def speak(self):
        return "..."  # default silent animal

# Define the Dog class here, inheriting from Animal
class Dog(Animal):
    def speak(self):
        return "Woof!"

# Define the Cat class here, inheriting from Animal
class Cat(Animal):
    def speak(self):
        return "Meow!"


In [ ]:
# Test polymorphism
animals = [Dog(), Cat(), Animal()]
for a in animals:
    print(a.speak())

Woof!
Meow!
...


### (8) Suppose you are analyzing the monthly temperatures (in °C) of two cities over three months.       

The data is stored in two Python lists:

```
city1 = [22.5, 23.1, 21.8]
city2 = [18.9, 19.3, 20.1]
```
           

**Your tasks:**
1. Use `np.array()` to convert these lists into a 2D NumPy array temps where each row represents a city and each column represents a month.        

2. Print the shape and data type (dtype) of the resulting array.       
     

In [ ]:
import numpy as np

city1 = [22.5, 23.1, 21.8]
city2 = [18.9, 19.3, 20.1]

temps = np.array([city1, city2])


print("Shape:", temps.shape)
print("Data type:", temps.dtype)


### (9) You are building a simple exam score management system for a university. Please do the following tasks using NumPy:

1. Use `np.ones()` to create a 3×4 array representing the scores of three students who got full marks (100 points) in all four quizzes.

2. Use `np.zeros()` to create a 2×4 array for two students who were absent for all quizzes (all scores are 0).

3. Use `np.full()` to create a 1×4 array for a student who scored 60 in every quiz.

4. Print the shape and the final score table.



In [ ]:
import numpy as np

# You code here
full_scores = np.ones((3, 4)) * 100


absent_scores = np.zeros((2, 4))


average_score = np.full((1, 4), 60)


print("Full score shape:", full_scores.shape)
print(full_scores)

print("Absent score shape:", absent_scores.shape)
print(absent_scores)

print("Average score shape:", average_score.shape)
print(average_score)


score_table = np.vstack((full_scores, absent_scores, average_score))


print("Final Score Table shape:", score_table.shape)
print("Final Score Table:\n", score_table)


Full score shape: (3, 4)
[[100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]]
Absent score shape: (2, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Average score shape: (1, 4)
[[60 60 60 60]]


### (10) Suppose you are designing three types of classroom layouts for a simulation system.



**You are asked to:**

1. Use `np.zeros()` to create a 4×5 array named `empty_room`, where all seats are empty (represented by 0).

2. Use `np.ones()` to create a 4×5 array named `full_room`, where all seats are occupied (represented by 1).

3. Use `np.full()` to create a 4×5 array named `mixed_room`, where all seats have a **default value of 9** (representing unknown seat status).

4. Print all three arrays and their shapes.

In [ ]:
import numpy as np

# You code here
# Create a 4x5 array for an empty room (all seats empty, represented by 0)
empty_room = np.zeros((4, 5), dtype=int)

# Create a 4x5 array for a full room (all seats occupied, represented by 1)
full_room = np.ones((4, 5), dtype=int)

# Create a 4x5 array for a mixed room (seats with a default value of 9, representing unknown seat status)
mixed_room = np.full((4, 5), 9, dtype=int)

# Print the arrays and their shapes
print("Empty Room:")
print(empty_room)
print("Shape:", empty_room.shape)

print("\nFull Room:")
print(full_room)
print("Shape:", full_room.shape)

print("\nMixed Room:")
print(mixed_room)
print("Shape:", mixed_room.shape)



Empty Room:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Shape: (4, 5)
Full Room:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape: (4, 5)
Mixed Room:
 [[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
Shape: (4, 5)
